#!/usr/bin/env bash
set -euo pipefail
# PHI Sovereign Continuous Monitor
# Auto-generated by Sovereign Autopilot

SCRIPT_DIR="/workspaces/dominion-os-demo-build/scripts"
MONITOR_INTERVAL="30"
SYNC_INTERVAL="60"
SYNC_SCRIPT="/workspaces/dominion-os-demo-build/scripts/phi_intelligent_sync.sh"
SYNC_STATE_FILE="/workspaces/dominion-os-demo-build/scripts/telemetry/.last_intelligent_sync"

while true; do
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    
    # Check PHI MCP Server
    if pgrep -f "main.py" > /dev/null 2>&1; then
        echo "[$TIMESTAMP] ✅ PHI MCP Server: OPERATIONAL"
    else
        echo "[$TIMESTAMP] ⚠️  PHI MCP Server: RESTARTING"
        cd /workspaces/phi-mcp-server
        source venv/bin/activate 2>/dev/null || true
        nohup python3 main.py > phi-server.log 2>&1 &
        sleep 2
        echo "[$TIMESTAMP] ✅ PHI MCP Server: RESTARTED by Sovereign Autopilot"
    fi
    
    # Monitor system resources
    MEM_USAGE=$(free -m | awk '/^Mem:/{printf "%.0f", $3/$2*100}')
    DISK_USAGE=$(df -h /workspaces | awk 'NR==2 {print $5}' | sed 's/%//')
    
    echo "[$TIMESTAMP] 📊 Memory: ${MEM_USAGE}% | Disk: ${DISK_USAGE}%"
    
    if [ -x "$SYNC_SCRIPT" ]; then
        NOW=$(date +%s)
        LAST_SYNC=$(cat "$SYNC_STATE_FILE" 2>/dev/null || echo 0)
        if [ $((NOW - LAST_SYNC)) -ge "$SYNC_INTERVAL" ]; then
            if bash "$SYNC_SCRIPT" >> "/workspaces/dominion-os-demo-build/scripts/telemetry/intelligent_sync.log" 2>&1; then
                echo "[$TIMESTAMP] 🔁 Intelligent sync completed"
            else
                echo "[$TIMESTAMP] ⚠️  Intelligent sync encountered issues"
            fi
            echo "$NOW" > "$SYNC_STATE_FILE"
        fi
    fi

    sleep "$MONITOR_INTERVAL"
done
