name: Deploy Demo to GitHub Pages
on:
  push:
    branches: [ demo ]   # <- use a dedicated 'demo' branch
permissions:
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }
      # (If you have a build step, do it here; otherwise copy static files.)
      - name: Prepare static site
        run: |
          rm -rf out && mkdir out
          cp -R public/* out/
          # scrub anything risky
          find out -type f -name "*.map" -delete
          find out -type f -name ".DS_Store" -delete
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with: { path: 'out' }
  deploy:
    needs: build
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
