# Dominion OS Demo - Google Cloud Build Configuration
# Optimized CI/CD pipeline for continuous deployment

options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: '100'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

substitutions:
  _SERVICE_NAME: dominion-demo-service
  _REGION: us-central1
  _PLATFORM: managed
  _MIN_INSTANCES: "1"
  _MAX_INSTANCES: "100"
  _MEMORY: 4Gi
  _CPU: "2"
  _TIMEOUT: 300s
  _CONCURRENCY: "250"

steps:
  # Step 1: Generate build tag and print info
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'build-info'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Generate a tag for this build
        if [ -z "$SHORT_SHA" ]; then
          BUILD_TAG="manual-$$(date +%Y%m%d-%H%M%S)"
        else
          BUILD_TAG="$$SHORT_SHA"
        fi
        echo "$$BUILD_TAG" > /workspace/BUILD_TAG

        echo "=========================================="
        echo "Dominion OS Demo - Cloud Build"
        echo "=========================================="
        echo "Branch: $${BRANCH_NAME:-manual}"
        echo "Commit: $${SHORT_SHA:-local}"
        echo "Build ID: $BUILD_ID"
        echo "Build Tag: $$BUILD_TAG"
        echo "Project: $PROJECT_ID"
        echo "Region: ${_REGION}"
        echo "=========================================="

  # Step 2: Run tests
  - name: 'python:3.12-slim'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --quiet pytest
        if [ -f requirements.txt ]; then
          pip install --quiet -r requirements.txt
        fi
        if [ -d tests ]; then
          echo "Running tests..."
          PYTHONPATH=. pytest -q tests/ || echo "No tests found, continuing..."
        else
          echo "No tests directory found, skipping tests"
        fi

  # Step 3: Build Docker image with cache
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BUILD_TAG=$$(cat /workspace/BUILD_TAG)
        docker build \
          --cache-from gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --tag gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$$BUILD_TAG \
          --tag gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest \
          .

  # Step 4: Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BUILD_TAG=$$(cat /workspace/BUILD_TAG)
        gcloud run deploy ${_SERVICE_NAME} \
          --image gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$$BUILD_TAG \
          --region ${_REGION} \
          --platform ${_PLATFORM} \
          --memory ${_MEMORY} \
          --cpu ${_CPU} \
          --timeout ${_TIMEOUT} \
          --concurrency ${_CONCURRENCY} \
          --min-instances ${_MIN_INSTANCES} \
          --max-instances ${_MAX_INSTANCES} \
          --no-cpu-throttling \
          --execution-environment gen2 \
          --allow-unauthenticated \
          --set-env-vars PROJECT_ID=$PROJECT_ID,REGION=${_REGION},SERVICE_NAME=${_SERVICE_NAME} \
          --labels managed-by=cloudbuild,build-tag=$$BUILD_TAG \
          --quiet

  # Step 6: Get service URL
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BUILD_TAG=$$(cat /workspace/BUILD_TAG)
        SERVICE_URL=$$(gcloud run services describe ${_SERVICE_NAME} \
          --region ${_REGION} \
          --platform ${_PLATFORM} \
          --format 'value(status.url)')
        echo "=========================================="
        echo "✅ Deployment Complete!"
        echo "Service URL: $$SERVICE_URL"
        echo "Image: gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$$BUILD_TAG"
        echo "=========================================="

  # Step 7: Run smoke test
  - name: 'gcr.io/cloud-builders/curl'
    id: 'smoke-test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$$(gcloud run services describe ${_SERVICE_NAME} \
          --region ${_REGION} \
          --platform ${_PLATFORM} \
          --format 'value(status.url)')
        echo "Running smoke test against $$SERVICE_URL/health"
        sleep 10
        curl -f -m 30 "$$SERVICE_URL/health" || echo "Health check endpoint not available"

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

# Build timeout
timeout: 1800s

# Build tags for organization
tags:
  - 'dominion-os'
  - 'demo-build'
  - 'cloud-run'
  - 'manual-deploy'
