FROM python:3.12-slim
WORKDIR /app
COPY requirements-prod.txt .
RUN pip install --no-cache-dir -r requirements-prod.txt
COPY command_core.py .
COPY bw.py .
COPY demo ./demo
COPY store ./store
COPY products ./products
COPY public_feeds ./public_feeds
EXPOSE 8080
CMD ["gunicorn", "--bind", ":8080", "bw:app"]
