# Samsung E-2139TSL Disk Cleanup Script (Windows)
# Generated by PHI Disk Cleanup Agent via AI Gateway
# Run as Administrator

Write-Host "╔════════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  Samsung E-2139TSL - Disk Cleanup Utility (Windows)           ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

$StartDate = Get-Date
$SpaceFreed = 0

# Check if running as Administrator
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "⚠️  Warning: Not running as Administrator. Some cleanup operations may be limited." -ForegroundColor Yellow
    Write-Host ""
}

Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host "📊 PRE-CLEANUP DISK ANALYSIS" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host ""

# Get disk space before cleanup
$DriveBefore = Get-PSDrive C
$FreeSpaceBefore = [math]::Round($DriveBefore.Free / 1GB, 2)
Write-Host "  C: Drive Free Space: $FreeSpaceBefore GB" -ForegroundColor Green
Write-Host ""

# 1. Clean Temp Files
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host "🗑️  STEP 1: Cleaning Temporary Files" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host ""

$TempPaths = @(
    "$env:TEMP",
    "$env:LOCALAPPDATA\Temp",
    "C:\Windows\Temp",
    "C:\Windows\Prefetch"
)

foreach ($TempPath in $TempPaths) {
    if (Test-Path $TempPath) {
        Write-Host "  Cleaning: $TempPath" -ForegroundColor Yellow
        try {
            Get-ChildItem -Path $TempPath -Recurse -Force -ErrorAction SilentlyContinue |
                Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
            Write-Host "  ✓ Cleaned" -ForegroundColor Green
        } catch {
            Write-Host "  ⚠️  Some files in use, skipped" -ForegroundColor Yellow
        }
    }
}
Write-Host ""

# 2. Clear Browser Cache
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host "🌐 STEP 2: Clearing Browser Caches" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host ""

$BrowserCaches = @(
    "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Cache",
    "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Code Cache",
    "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default\Cache",
    "$env:LOCALAPPDATA\Mozilla\Firefox\Profiles\*\cache2"
)

foreach ($CachePath in $BrowserCaches) {
    if (Test-Path $CachePath) {
        Write-Host "  Clearing: $(Split-Path $CachePath -Parent | Split-Path -Leaf)" -ForegroundColor Yellow
        try {
            Remove-Item -Path $CachePath -Recurse -Force -ErrorAction SilentlyContinue
            Write-Host "  ✓ Cleared" -ForegroundColor Green
        } catch {
            Write-Host "  ⚠️  Browser may be running, skipped" -ForegroundColor Yellow
        }
    }
}
Write-Host ""

# 3. Empty Recycle Bin
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host "🗑️  STEP 3: Emptying Recycle Bin" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host ""

try {
    Clear-RecycleBin -Force -ErrorAction SilentlyContinue
    Write-Host "  ✓ Recycle Bin emptied" -ForegroundColor Green
} catch {
    Write-Host "  ⚠️  Recycle Bin already empty or access denied" -ForegroundColor Yellow
}
Write-Host ""

# 4. Windows Update Cleanup
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host "🔄 STEP 4: Windows Update Cleanup" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host ""

Write-Host "  Running DISM cleanup (this may take a few minutes)..." -ForegroundColor Yellow
try {
    $null = Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase
    Write-Host "  ✓ Windows component cleanup complete" -ForegroundColor Green
} catch {
    Write-Host "  ⚠️  Requires Administrator privileges" -ForegroundColor Yellow
}
Write-Host ""

# 5. Disk Cleanup Utility
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host "🧹 STEP 5: Running Windows Disk Cleanup" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host ""

Write-Host "  Launching Disk Cleanup utility..." -ForegroundColor Yellow
Start-Process cleanmgr -ArgumentList '/sagerun:1' -Wait
Write-Host "  ✓ Disk Cleanup complete" -ForegroundColor Green
Write-Host ""

# 6. Find Large Files
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host "📁 STEP 6: Identifying Large Files" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host ""

Write-Host "  Top 10 largest files on C: drive:" -ForegroundColor Yellow
Get-ChildItem C:\ -Recurse -File -ErrorAction SilentlyContinue |
    Sort-Object Length -Descending |
    Select-Object -First 10 |
    Format-Table @{Label="Size (GB)";Expression={[math]::Round($_.Length/1GB,2)}}, FullName -AutoSize

Write-Host ""

# Final Report
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host "📊 POST-CLEANUP ANALYSIS" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Blue
Write-Host ""

$DriveAfter = Get-PSDrive C
$FreeSpaceAfter = [math]::Round($DriveAfter.Free / 1GB, 2)
$SpaceFreed = [math]::Round(($FreeSpaceAfter - $FreeSpaceBefore), 2)

Write-Host "  Before Cleanup: $FreeSpaceBefore GB free" -ForegroundColor Yellow
Write-Host "  After Cleanup:  $FreeSpaceAfter GB free" -ForegroundColor Green
Write-Host ""
Write-Host "  ✅ Space Freed: $SpaceFreed GB" -ForegroundColor Green
Write-Host ""

$Duration = (Get-Date) - $StartDate
Write-Host "  ⏱️  Cleanup Duration: $($Duration.Minutes)m $($Duration.Seconds)s" -ForegroundColor Cyan
Write-Host ""

Write-Host "╔════════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  ✅ CLEANUP COMPLETE                                           ║" -ForegroundColor Green
Write-Host "╚════════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""

Write-Host "Press any key to exit..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
