#!/bin/bash

# Samsung E-2139TSL Disk Cleanup Script (Linux)
# Generated by PHI Disk Cleanup Agent via AI Gateway

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  Samsung E-2139TSL - Disk Cleanup Utility (Linux)             ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

START_TIME=$(date +%s)

# Check for sudo access
if [ "$EUID" -ne 0 ]; then
    echo -e "${YELLOW}⚠️  Warning: Not running as root. Some cleanup operations may require sudo.${NC}"
    echo ""
fi

# Pre-cleanup analysis
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}📊 PRE-CLEANUP DISK ANALYSIS${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

BEFORE_SPACE=$(df / | awk 'NR==2 {print $4}')
echo -e "  Root (/) Available: ${GREEN}$(df -h / | awk 'NR==2 {print $4}')${NC}"
echo ""

# 1. Clean Package Cache
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}📦 STEP 1: Cleaning Package Cache${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

if command -v apt &> /dev/null; then
    echo -e "  ${YELLOW}Cleaning apt cache...${NC}"
    sudo apt clean
    sudo apt autoclean
    sudo apt autoremove -y
    echo -e "  ${GREEN}✓ APT cache cleaned${NC}"
elif command -v dnf &> /dev/null; then
    echo -e "  ${YELLOW}Cleaning dnf cache...${NC}"
    sudo dnf clean all
    sudo dnf autoremove -y
    echo -e "  ${GREEN}✓ DNF cache cleaned${NC}"
elif command -v yum &> /dev/null; then
    echo -e "  ${YELLOW}Cleaning yum cache...${NC}"
    sudo yum clean all
    sudo yum autoremove -y
    echo -e "  ${GREEN}✓ YUM cache cleaned${NC}"
fi
echo ""

# 2. Clean System Logs
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}📝 STEP 2: Cleaning System Logs${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

if command -v journalctl &> /dev/null; then
    echo -e "  ${YELLOW}Cleaning journal logs (keeping last 7 days)...${NC}"
    sudo journalctl --vacuum-time=7d
    echo -e "  ${GREEN}✓ Journal logs cleaned${NC}"
fi

echo -e "  ${YELLOW}Cleaning old log files...${NC}"
sudo find /var/log -type f -name "*.log" -mtime +30 -delete 2>/dev/null
sudo find /var/log -type f -name "*.gz" -delete 2>/dev/null
echo -e "  ${GREEN}✓ Old log files removed${NC}"
echo ""

# 3. Clean Temp Files
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}🗑️  STEP 3: Cleaning Temporary Files${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo -e "  ${YELLOW}Cleaning /tmp...${NC}"
sudo rm -rf /tmp/*
echo -e "  ${YELLOW}Cleaning /var/tmp...${NC}"
sudo rm -rf /var/tmp/*
echo -e "  ${YELLOW}Cleaning user temp...${NC}"
rm -rf ~/.cache/thumbnails/*
echo -e "  ${GREEN}✓ Temp files cleaned${NC}"
echo ""

# 4. Clean Browser Cache
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}🌐 STEP 4: Cleaning Browser Caches${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

[ -d ~/.cache/google-chrome ] && rm -rf ~/.cache/google-chrome/* && echo -e "  ${GREEN}✓ Chrome cache cleared${NC}"
[ -d ~/.cache/chromium ] && rm -rf ~/.cache/chromium/* && echo -e "  ${GREEN}✓ Chromium cache cleared${NC}"
[ -d ~/.cache/mozilla ] && rm -rf ~/.cache/mozilla/* && echo -e "  ${GREEN}✓ Firefox cache cleared${NC}"
echo ""

# 5. Docker Cleanup (if installed)
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}🐳 STEP 5: Docker Cleanup${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

if command -v docker &> /dev/null; then
    echo -e "  ${YELLOW}Pruning Docker system...${NC}"
    docker system prune -af --volumes
    echo -e "  ${GREEN}✓ Docker cleaned${NC}"
else
    echo -e "  ${YELLOW}Docker not installed, skipping${NC}"
fi
echo ""

# 6. Find Large Files
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}📁 STEP 6: Identifying Large Files${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo -e "  ${YELLOW}Top 10 largest files in home directory:${NC}"
echo ""
find ~ -type f -exec du -h {} + 2>/dev/null | sort -rh | head -10
echo ""

# Post-cleanup analysis
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}📊 POST-CLEANUP ANALYSIS${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

AFTER_SPACE=$(df / | awk 'NR==2 {print $4}')
SPACE_FREED=$(( ($AFTER_SPACE - $BEFORE_SPACE) / 1024 ))

echo -e "  Root (/) Available: ${GREEN}$(df -h / | awk 'NR==2 {print $4}')${NC}"
echo ""
echo -e "  ${GREEN}✅ Space Freed: ${SPACE_FREED} MB${NC}"
echo ""

END_TIME=$(date +%s)
DURATION=$(( $END_TIME - $START_TIME ))

echo -e "  ${CYAN}⏱️  Cleanup Duration: ${DURATION}s${NC}"
echo ""

echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  ✅ CLEANUP COMPLETE                                           ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
