name: Proof HTML Lint (No External CDNs)

on:
    pull_request:
        branches: ["main", "release/**"]
    workflow_dispatch:

jobs:
    no-cdn:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Ensure no external CDN references
              run: |
                  set -euo pipefail
                  # Scan web assets for external URLs
                  if grep -RInE "https?://" web/ ; then
                    echo "External URL references found in web/ (CDNs not allowed)" >&2
                    exit 1
                  fi
                  echo "OK: no external references"
