name: CI (build+test)
on:
  pull_request:
    branches:
      - "main"
      - "release/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build ok"
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "tests ok"
