name: continuous-polish
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  polish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Run Prettier (safe formats only)
        run: |
          npx --yes prettier@3 --write "**/*.{md,mdx,json,yml,yaml}" || true
      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: autopolish"
          branch: main
