name: Guardrails Audit
on:
  pull_request:
    branches: [ "main", "release/**" ]
jobs:
  audit:
    # Read contents is enough for GH API calls with GITHUB_TOKEN
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Ensure gh cli
        run: |
          if ! command -v gh >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y gh
          fi

      - name: Assert repo guardrails
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          function Die($m){ Write-Error $m; exit 1 }
          $ownerRepo = "${{ github.repository }}"

          $protJson = gh api -H "Accept: application/vnd.github+json" "repos/$ownerRepo/branches/main/protection"
          if (-not $protJson) { Die "No branch protection on main." }
          $prot = $protJson | ConvertFrom-Json

          # Collect required checks from both shapes
          $req = @($prot.required_status_checks.checks.context) + @($prot.required_status_checks.contexts) | Where-Object { $_ }

          $need = @("build","test")
          $missing = @($need | Where-Object { $_ -notin $req })

          if ($missing.Count -gt 0) { Die "Missing required checks: $($missing -join ', ') | present: $($req -join ', ')" }
          if (-not $prot.required_conversation_resolution.enabled) { Die "Conversation resolution is not enforced." }
          if (-not $prot.required_linear_history.enabled) { Die "Linear history is not enforced." }

          "Guardrails OK."
