name: heartbeat-commit
on:
  schedule: [{ cron: "*/30 * * * *" }]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  beat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update heartbeat
        run: |
          mkdir -p telemetry
          date -u +"%Y-%m-%dT%H:%M:%SZ" > telemetry/heartbeat.txt
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add telemetry/heartbeat.txt
          git commit -m "chore: heartbeat" || exit 0
          git push
